import 'package:flutter/material.dart';
import 'package:quickhire/models/company.dart';
import 'package:quickhire/models/job.dart';

const double horizontalPadding = 16;
const double verticalPadding = 8;
const double largeFontSize = 20;
const double mediumFontSize = 16;
const double smallFontSize = 13;

const FontWeight poppinsLight = FontWeight.w300;
const FontWeight poppinsRegular = FontWeight.w400;
const FontWeight poppinsSemiBold = FontWeight.w600;

// const String BASE_URL = "http://172.232.110.90:80";
const String BASE_URL = "http://147.93.103.103";
const String IMAGE_URL = "http://172.232.110.90:80/var/www/quickhire";
Uri termsUrl = Uri.parse(
  'http://172.232.110.90/terms-and-conditions/',
);
Uri policyUrl = Uri.parse(
  'http://172.232.110.90/privacy-policy/',
);

List<Job> emptyJob = List.filled(
    3,
    Job(
      jobId: 101,
      role: 'Senior Software Engineer',
      company: Company(
        companyId: 1,
        companyName: 'Tech Innovators Inc.',
        companyTitle: 'Leading Tech Company',
        companyDesc: 'A company dedicated to pioneering technology solutions.',
        companyLink: '',
        linkedinLink: '',
        industry: 'Technology',
        foundedYear: '2010',
        companyLogo: '',
        companyBackground: '',
        location: 'San Francisco, USA',
        isApproved: true,
        isCreated: '2024-01-01T10:00:00Z',
        isUpdated: '2024-01-01T10:00:00Z',
        userDetails: 123,
      ),
      expectedSalary: '₹120,000 - ₹150,000',
      jobType: 'Full-time',
      jobDesc:
          'Responsible for designing, developing, and maintaining software solutions.',
      skills: 'Flutter, Django, Python, React',
      isActive: true,
      isCreated: '2024-01-15T09:00:00Z',
      isUpdated: '2024-01-20T14:30:00Z',
    ));

final List<String> skills = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "TypeScript",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Bootstrap",
  "SASS/LESS",
  "Flutter",
  "React Native",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "scikit-learn",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Spring Boot",
  "Laravel",
  "Express.js",
  "Blockchain",
  "AR/VR",
  "IoT",
  "Cybersecurity",
  "Microservices",
  "GraphQL",
  "WebAssembly",
  "Data Analysis",
  "Project Management",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "UX/UI Design",
  "Wireframing",
  "Prototyping",
  "SEO",
  "Content Marketing",
  "Social Media Marketing",
  "Email Marketing",
  "Salesforce",
  "CRM Systems",
  "Customer Service",
  "Negotiation Skills",
  "Public Speaking",
  "Technical Writing",
  "Data Visualization",
  "Business Analysis",
  "Financial Analysis",
  "Excel",
  "Power BI",
  "Tableau",
  "Photoshop",
  "Illustrator",
  "After Effects",
  "Video Editing",
  "Animation",
  "3D Modeling",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Robotics",
  "Embedded Systems",
  "Database Administration",
  "System Administration",
  "Network Security",
  "Cloud Architecture",
  "Ethical Hacking",
  "Penetration Testing",
  "IT Support",
  "Technical Support",
  "Legal Research",
  "Project Coordination",
  "Team Leadership",
  "Time Management",
  "Strategic Planning",
  "Negotiation",
  "Conflict Resolution",
  "Presentation Skills",
  "Research Skills",
  "Teamwork",
  "Problem-Solving",
  "Critical Thinking",
  "Leadership",
  "Digital Marketing",
  "Copywriting",
  "Data Entry",
  "Market Research",
  "Sales Strategy",
  "Budgeting",
  "Risk Management",
  "Quality Assurance",
  "System Integration",
  "DevOps",
  "ITIL",
  "Customer Relationship Management",
  "Enterprise Resource Planning",
  "Workflow Automation",
  "API Integration",
  "User Experience Research",
  "User Interface Design",
  "Information Security",
  "Compliance Management",
  "Business Intelligence",
  "Data Warehousing",
  "Data Mining",
  "Cloud Computing",
  "Virtualization",
  "Augmented Reality",
  "DevSecOps",
  "Performance Optimization",
  "Mobile App Development",
  "Desktop App Development",
  "E-commerce",
  "Retail Management",
  "Logistics Management",
  "Supply Chain Management",
  "Inventory Management",
  "Human Resources Management",
  "Recruiting",
  "Talent Acquisition",
  "Employee Training",
  "Compensation and Benefits",
  "Organizational Development",
  "Change Management",
  "Process Improvement",
  "Lean Management",
  "Six Sigma",
  "Quality Control",
  "Software Testing",
  "Automation Testing",
  "Manual Testing",
  "Functional Testing",
  "Regression Testing",
  "User Acceptance Testing",
  "System Testing",
  "Integration Testing",
  "Acceptance Criteria",
  "Bug Tracking",
  "Issue Resolution",
  "Release Management",
  "Version Control",
  "Continuous Integration",
  "Continuous Delivery",
  "Agile Coaching",
  "Scrum Master",
  "Kanban Board Management",
  "Sprint Planning",
  "Retrospective Facilitation",
  "Product Roadmap Planning",
  "Stakeholder Management",
  "Customer Feedback Analysis",
  "Feature Prioritization",
  "A/B Testing",
  "Usability Testing",
  "Cross-Browser Testing",
  "Mobile Testing",
  "Cloud Migration",
  "Data Security",
  "Incident Management",
  "Threat Analysis",
  "Firewall Management",
  "Intrusion Detection",
  "Network Administration",
  "Server Management",
  "Backup and Recovery",
  "Disaster Recovery Planning",
  "IT Governance",
  "Compliance Auditing",
  "Systems Analysis",
  "Process Documentation",
  "Application Support",
  "Systems Configuration",
  "Technical Troubleshooting",
  "Data Cleaning",
  "Data Integration",
  "Data Transformation",
  "Report Generation",
  "Dashboard Creation",
  "Business Process Automation",
  "Resource Allocation",
  "Vendor Management",
  "Contract Negotiation",
  "Budget Management",
  "Forecasting",
  "Strategic Analysis",
  "Operational Efficiency",
  "Customer Onboarding",
  "Training and Development",
  "Talent Management",
  "Organizational Strategy",
  "Digital Transformation",
  "Risk Assessment",
  "Compliance Training",
  "Ethical Standards",
  "Corporate Governance",
  "Legal Compliance",
  "Intellectual Property Management",
  "Crisis Management",
  "Health and Safety Management",
  "Environmental Management",
  "Sustainability Practices",
  "Corporate Social Responsibility",
  "Public Relations",
  "Media Relations",
  "Event Planning",
  "Fundraising",
  "Grant Writing",
  "Policy Development",
  "Regulatory Affairs",
  "Advocacy",
  "Community Outreach",
  "Stakeholder Engagement",
  "Strategic Partnerships",
  "Market Positioning",
  "Competitive Analysis",
  "Brand Management",
  "Product Development",
  "Customer Insights",
  "Sales Forecasting",
  "Market Segmentation",
  "Product Launch",
  "Customer Retention",
  "Lead Generation",
  "Demand Generation",
  "Channel Management",
  "Franchise Management",
  "Licensing",
  "Business Development",
  "Strategic Alliances",
  "Contract Management",
  "Negotiation Tactics",
  "Business Case Development",
  "Performance Metrics",
  "Key Performance Indicators",
  "Process Mapping",
  "Business Process Reengineering",
  "Workflow Design",
  "Automation Tools",
  "Document Management",
  "Knowledge Management",
  "Information Management",
  "Risk Mitigation",
  "Change Control",
  "Configuration Management",
  "Incident Response",
  "Security Policies",
  "Threat Mitigation",
  "Vulnerability Assessment",
  "Security Operations",
  "Secure Coding Practices",
  "Network Design",
  "Wireless Networking",
  "Database Design",
  "System Design",
  "Infrastructure Planning",
  "Enterprise Architecture"
];

final List<String> languages = [
  // Indian Languages
  'Hindi', 'Bengali', 'Telugu', 'Marathi', 'Tamil', 'Urdu', 'Gujarati',
  'Malayalam', 'Kannada', 'Odia', 'Punjabi', 'Assamese', 'Maithili',
  'Sanskrit', 'Konkani', 'Sindhi', 'Nepali', 'Manipuri', 'Bodo',
  'Santhali', 'Sora', 'Khasi', 'Mizo', 'Cherokee', 'Tulu', 'Dogri',
  'Kashmiri', 'Shiva', 'Pali',

  // Foreign Languages
  'English', 'Mandarin Chinese', 'Spanish', 'French', 'German', 'Portuguese',
  'Russian', 'Japanese', 'Korean', 'Arabic', 'Turkish', 'Italian', 'Dutch',
  'Swedish', 'Danish', 'Norwegian', 'Finnish', 'Polish', 'Ukrainian',
  'Hebrew', 'Thai', 'Vietnamese', 'Indonesian', 'Malay', 'Filipino',
  'Hausa', 'Swahili', 'Zulu', 'Xhosa', 'Amharic', 'Georgian', 'Armenian',
  'Kazakh', 'Uzbek', 'Tajik', 'Persian', 'Pashto', 'Kurdish', 'Punjabi',
  'Tamil', 'Sinhala', 'Burmese', 'Nepali', 'Mongolian', 'Macedonian',
  'Serbo-Croatian', 'Albanian', 'Bosnian', 'Montenegrin', 'Slovak', 'Czech',
  'Hungarian', 'Latvian', 'Lithuanian', 'Estonian', 'Icelandic',
  'Luxembourgish', 'Catalan', 'Galician', 'Basque'
];
